= RISC-V Load/Store Pair (LSP) instructions

The Zilsp extension adds support for loads and stores using aligned register pairs. It is an RV32-only extension, reusing existing RV64 encodings.

= License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0).
See the link:LICENSE[LICENSE] file for details.

= Dependencies

To build the document, you'll need the following tools installed on your system:

```
  Make
  asciiDoctor-pdf
```

= Cloning and Building the Document

This project uses submodules to include the RISC-V documentation toolchain. 

```
  git clone --recurse-submodule https://github.com/NXP/riscv-zilsp
  cd ./riscv-zilsp.git
  make VERSION=v0.8.1-draft REVMARK=Draft
```

`VERSION`: Represents the version of the specification being built. By default, this is set to 'v0.0.0'. You can change this to a different value, like 'v1.0.0', 'v1.1.0', etc., based on the current version of your specification.

`REVMARK`: This represents a revision marker for the project. Its default value is 'Draft'. You may want to change this to something like 'Release', 'Stable' or 'Ratified'.
